# official doc 
# https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml

name: Python application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm' # i consulted LLM to understand npm

    - name: configure environment
      run: |
        uv init -p 3.10
        
    - name: Install dependencies node.js
      run: npm ci
    - name: Install dependencies python
      run: |
        uv init -p 3.10
        uv add -r requirements.txt

  clean:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        # polish the format
    - name: Code format with Prettier
      run: |
        npx prettier --write "**/*.{py,md,js,json,css,html}"
    - name: Quality gates
      run: |
        npx eslint . --max-warnings=0
        npx prettier --check . --config .prettierrc
  test:
    runs-on: ubuntu-latest
    needs: [build, clean]
    steps:

    - name: Test with pytest
      run: pytest tests.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml \
        --cov-fail-under=80 
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      if: ${{ always() }}
    - name: threshold coverage
      run: 
